### ISSUE TITLE
Dataset cannot be downloaded

### ISSUE THREAD

**Issue by fernandobperezm** [Alice1998/MakeFairnessMoreFair#1]
Hello! Thanks in advance for your contribution!

I could not  download the dataset as the website faces an "Internal Server Error". Could you please provide an alternative link to download the dataset? (see screenshot attached)

<img width="1432" alt="Screenshot 2022-08-17 at 14 48 56" src="https://user-images.githubusercontent.com/10052938/185219286-ed7e3ed9-4827-45cf-a371-747a87c2dd5a.png">

Best regards!

**Comment by Alice1998** [comment]
hello
I have also uploaded a copy on google drive, see here.

**Comment by Alice1998** [comment]
https://drive.google.com/drive/folders/1Xw4Xr4HQYM9L3NBdB-TuVNL9FzK4-egl?usp=sharing

**Comment by Alice1998** [comment]
Hi, thanks for your feedback.
Here is a copy of the dataset on Google Drive.
https://drive.google.com/drive/folders/1Xw4Xr4HQYM9L3NBdB-TuVNL9FzK4-egl?usp=sharing
Impression log files are still uploading and it may take some time.
