### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by ADCa97** [Alice1998/MakeFairnessMoreFair#2]
Hello! Thanks in advance for your contribution!
When I run the following command
`python sequence_generation/generate.py --model_name BUIR --emb_size 64 --lr 1e-3 --l2 1e-6 --dataset 'kwai_fair'`,
it throws an error
 `FileNotFoundError: [Errno 2] No such file or directory: '../../model/BUIR/BUIR__kwai_fair__0__lr=0.001__l2=1e-06__emb_size=64__momentum=0.995_testAll.npy'`.
I couldnot find any code that generates the `XXX_testAll.npy` file.

**Comment by Alice1998** [comment]
This .npy file is generated by ReChorus to store the top K recommendation lists for the test instances. I will update the modification part under the ReChorus folders in two days.

Bests.
